import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../api/client'
import './pages.css'

/** Mirrors server/Models/GenDtos.cs DocumentTemplateListItemDto (subset used for the picker). */
interface DocumentTemplateListItemDto {
  id: string
  name: string
  isActive: boolean
}

/** Mirrors server/Models/GenDtos.cs GeneratedDocumentListItemDto. */
interface GeneratedDocumentListItemDto {
  id: string
  documentTemplateId: string
  templateName: string
  generatedByUserId: string
  generatedAt: string
  isArchived: boolean
  archivedDocumentId: string | null
}

/** Mirrors server/Models/CabinetDtos.cs CabinetDto (subset used for the picker). */
interface CabinetDto {
  id: string
  name: string
}

/** Mirrors server/Models/DocumentTypeDtos.cs DocumentTypeDto (subset used for the picker). */
interface DocumentTypeDto {
  id: string
  cabinetId: string
  name: string
}

/** Mirrors server/Models/GenDtos.cs GenerationPushTarget. */
type GenerationPushTarget = 'None' | 'Archive'

interface CreateGeneratedDocumentForm {
  documentTemplateId: string
  dataJson: string
  pushTo: GenerationPushTarget
  cabinetId: string
  documentTypeId: string
}

async function fetchGeneratedDocuments(): Promise<GeneratedDocumentListItemDto[]> {
  const { data } = await api.get<GeneratedDocumentListItemDto[]>('/api/generated-documents')
  return data
}

async function fetchTemplates(): Promise<DocumentTemplateListItemDto[]> {
  const { data } = await api.get<DocumentTemplateListItemDto[]>('/api/document-templates')
  return data
}

async function fetchCabinets(): Promise<CabinetDto[]> {
  const { data } = await api.get<CabinetDto[]>('/api/cabinets')
  return data
}

async function fetchDocumentTypes(cabinetId: string): Promise<DocumentTypeDto[]> {
  const { data } = await api.get<DocumentTypeDto[]>(`/api/cabinets/${cabinetId}/document-types`)
  return data
}

async function createGeneratedDocument(form: CreateGeneratedDocumentForm) {
  const { data } = await api.post('/api/generated-documents', {
    documentTemplateId: form.documentTemplateId,
    dataJson: form.dataJson,
    pushTo: form.pushTo,
    cabinetId: form.pushTo === 'Archive' ? form.cabinetId : null,
    documentTypeId: form.pushTo === 'Archive' ? form.documentTypeId : null,
  })
  return data
}

function formatDate(value: string): string {
  return new Date(value).toLocaleString()
}

export default function GeneratedDocumentsPage() {
  const queryClient = useQueryClient()
  const [isCreateOpen, setCreateOpen] = useState(false)

  const generatedQuery = useQuery({ queryKey: ['generatedDocuments'], queryFn: fetchGeneratedDocuments })

  return (
    <section>
      <div className="page-head">
        <div>
          <h1>Generated Documents</h1>
          <div className="page-sub">
            PDFs rendered from document templates, optionally pushed into an archive cabinet.
          </div>
        </div>
        <button type="button" className="btn primary" onClick={() => setCreateOpen(true)}>
          Generate
        </button>
      </div>

      {generatedQuery.isLoading && <div className="empty-state">Loading generated documents…</div>}
      {generatedQuery.isError && <div className="empty-state">Could not load generated documents.</div>}

      {generatedQuery.data && (
        <div className="panel">
          {generatedQuery.data.length === 0 && (
            <div className="empty-state">
              No documents generated yet. Generate one from a template to see it here.
            </div>
          )}
          {generatedQuery.data.length > 0 && (
            <table className="data-table">
              <thead>
                <tr>
                  <th>Template</th>
                  <th>Generated by</th>
                  <th>Generated at</th>
                  <th>Archived</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {generatedQuery.data.map((gen) => (
                  <tr key={gen.id}>
                    <td>{gen.templateName}</td>
                    <td>{gen.generatedByUserId}</td>
                    <td>{formatDate(gen.generatedAt)}</td>
                    <td>
                      <span className={`status${gen.isArchived ? ' ok' : ''}`}>
                        {gen.isArchived ? 'Archived' : 'Standalone'}
                      </span>
                    </td>
                    <td>
                      <div style={{ display: 'flex', gap: 12, justifyContent: 'flex-end', alignItems: 'center' }}>
                        {gen.archivedDocumentId && (
                          <Link className="crumb" to={`/documents/${gen.archivedDocumentId}`}>
                            View document
                          </Link>
                        )}
                        <a
                          className="btn sm"
                          href={`/api/generated-documents/${gen.id}/content`}
                          target="_blank"
                          rel="noreferrer"
                        >
                          Download
                        </a>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {isCreateOpen && (
        <GenerateModal
          onClose={() => setCreateOpen(false)}
          onGenerated={() => {
            setCreateOpen(false)
            queryClient.invalidateQueries({ queryKey: ['generatedDocuments'] })
          }}
        />
      )}
    </section>
  )
}

interface GenerateModalProps {
  onClose: () => void
  onGenerated: () => void
}

function GenerateModal({ onClose, onGenerated }: GenerateModalProps) {
  const [documentTemplateId, setDocumentTemplateId] = useState('')
  const [dataJson, setDataJson] = useState('')
  const [pushTo, setPushTo] = useState<GenerationPushTarget>('None')
  const [cabinetId, setCabinetId] = useState('')
  const [documentTypeId, setDocumentTypeId] = useState('')
  const [formError, setFormError] = useState<string | null>(null)

  const templatesQuery = useQuery({ queryKey: ['documentTemplates'], queryFn: fetchTemplates })
  const cabinetsQuery = useQuery({
    queryKey: ['cabinets'],
    queryFn: fetchCabinets,
    enabled: pushTo === 'Archive',
  })
  const documentTypesQuery = useQuery({
    queryKey: ['documentTypes', cabinetId],
    queryFn: () => fetchDocumentTypes(cabinetId),
    enabled: pushTo === 'Archive' && !!cabinetId,
  })

  const createMutation = useMutation({
    mutationFn: createGeneratedDocument,
    onSuccess: onGenerated,
    onError: () => setFormError('Could not generate the document. Check the template and data, then try again.'),
  })

  const activeTemplates = (templatesQuery.data ?? []).filter((t) => t.isActive)

  function handleCabinetChange(value: string) {
    setCabinetId(value)
    setDocumentTypeId('')
  }

  function handleSubmit(event: FormEvent) {
    event.preventDefault()
    if (!documentTemplateId) {
      setFormError('Choose a template.')
      return
    }
    if (!dataJson.trim()) {
      setFormError('Data is required.')
      return
    }
    try {
      JSON.parse(dataJson)
    } catch {
      setFormError('Data is not valid JSON.')
      return
    }
    if (pushTo === 'Archive' && (!cabinetId || !documentTypeId)) {
      setFormError('Choose a cabinet and document type to push this into the archive.')
      return
    }
    setFormError(null)
    createMutation.mutate({ documentTemplateId, dataJson, pushTo, cabinetId, documentTypeId })
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-panel wide" onClick={(e) => e.stopPropagation()}>
        <h2>Generate document</h2>
        <p className="modal-sub">
          Pick a template and supply the data to merge into it. Optionally push the result straight
          into an archive cabinet.
        </p>
        <form className="form-grid" onSubmit={handleSubmit}>
          <div>
            <label className="field-label" htmlFor="gen-template">Template</label>
            {templatesQuery.isLoading && <div className="empty-state">Loading templates…</div>}
            {templatesQuery.data && (
              <select
                id="gen-template"
                className="field-input"
                value={documentTemplateId}
                onChange={(e) => setDocumentTemplateId(e.target.value)}
                autoFocus
              >
                <option value="">Select…</option>
                {activeTemplates.map((tpl) => (
                  <option key={tpl.id} value={tpl.id}>{tpl.name}</option>
                ))}
              </select>
            )}
          </div>
          <div>
            <label className="field-label" htmlFor="gen-data">Data (JSON)</label>
            <textarea
              id="gen-data"
              className="code-textarea sm"
              value={dataJson}
              onChange={(e) => setDataJson(e.target.value)}
              placeholder={'{ "order": { "doc_num": 1001, "card_name": "Acme LLC" } }'}
              spellCheck={false}
            />
          </div>
          <div className="field-row">
            <div>
              <label className="field-label" htmlFor="gen-push-to">Push to</label>
              <select
                id="gen-push-to"
                className="field-input"
                value={pushTo}
                onChange={(e) => setPushTo(e.target.value as GenerationPushTarget)}
              >
                <option value="None">Nowhere (standalone PDF)</option>
                <option value="Archive">Archive cabinet</option>
              </select>
            </div>
            {pushTo === 'Archive' && (
              <div>
                <label className="field-label" htmlFor="gen-cabinet">Cabinet</label>
                {cabinetsQuery.data && (
                  <select
                    id="gen-cabinet"
                    className="field-input"
                    value={cabinetId}
                    onChange={(e) => handleCabinetChange(e.target.value)}
                  >
                    <option value="">Select…</option>
                    {cabinetsQuery.data.map((cab) => (
                      <option key={cab.id} value={cab.id}>{cab.name}</option>
                    ))}
                  </select>
                )}
              </div>
            )}
          </div>
          {pushTo === 'Archive' && cabinetId && (
            <div>
              <label className="field-label" htmlFor="gen-document-type">Document type</label>
              {documentTypesQuery.isLoading && <div className="empty-state">Loading document types…</div>}
              {documentTypesQuery.data && (
                <select
                  id="gen-document-type"
                  className="field-input"
                  value={documentTypeId}
                  onChange={(e) => setDocumentTypeId(e.target.value)}
                >
                  <option value="">Select…</option>
                  {documentTypesQuery.data.map((dt) => (
                    <option key={dt.id} value={dt.id}>{dt.name}</option>
                  ))}
                </select>
              )}
            </div>
          )}
          {formError && <p className="form-error">{formError}</p>}
          <div className="modal-actions">
            <button type="button" className="btn" onClick={onClose}>Cancel</button>
            <button type="submit" className="btn primary" disabled={createMutation.isPending}>
              {createMutation.isPending ? 'Generating…' : 'Generate'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
