namespace NexusDocs.Api.Infrastructure.Capture;

/// <summary>
/// Text-extraction abstraction for the CAPTURE module's document ingest pipeline
/// (ARCHITECTURE.md section 7, "A/P invoice automation"). A document lands as a PDF (from the
/// hot folder or a monitored mailbox) and the pipeline needs its raw text before classification
/// and header/line extraction (see Classification/heuristics code) can run.
///
/// SCOPE (read this before wiring up a new provider or "fixing" the OCR gap): this environment
/// has no Tesseract OCR binary installed and no paid cloud OCR service credentials (Azure
/// Document Intelligence etc.) — wiring one in is an explicit product-owner decision tracked as
/// an open item in ARCHITECTURE.md section 11 item 5 ("OCR accuracy commitment"), the same way
/// the SIGN module's PDF-signing-library choice was left open. Two providers exist today:
///
///   1. <see cref="PdfPigTextProvider"/> — the PRIMARY, fully-working path. It uses the free,
///      MIT-licensed, pure-C# "PdfPig" NuGet package to pull the embedded text layer straight out
///      of a PDF. This covers real ground: most real invoices are generated by accounting
///      software and already carry a text layer, so this is not a stub for the flagship scenario
///      — it's the actual extraction path for a large fraction of real invoices.
///
///   2. <see cref="TesseractCliOcrProvider"/> — the SECONDARY path for genuinely scanned/
///      image-only PDFs (no text layer). It shells out to the "tesseract" CLI and is real,
///      correctly-written code against Tesseract's documented CLI contract, but it has NOT been
///      run against a real tesseract binary in this environment (none is installed) — see its own
///      doc comment for exactly what does and doesn't work, including the important gap that
///      PDF-to-image rasterization is NOT implemented in this phase (no rasterizer library/tool
///      confirmed present either) — this provider currently only accepts pre-rasterized image
///      bytes (PNG/JPEG), not PDF bytes. Full scanned-PDF OCR support needs a rasterization step
///      (e.g. via "pdftoppm" or "magick") wired in as a follow-up once that dependency is decided.
///
/// <see cref="CompositeOcrProvider"/> is what callers should actually inject (see DI registration
/// in Program.cs) — it tries PdfPig first and only attempts the Tesseract fallback when PdfPig's
/// result looks like a scanned image AND tesseract is actually available on PATH, so pipeline
/// code never needs to know which provider ultimately did the work.
/// </summary>
public interface IOcrProvider
{
    /// <summary>Short, human-readable name for logging/diagnostics (e.g. "PdfPig", "Tesseract CLI").</summary>
    string ProviderName { get; }

    /// <summary>
    /// Extracts text from the given content stream. The stream's position is left at an
    /// unspecified point after this call; callers that need to reuse it should seek back to 0 (or
    /// pass a fresh stream/copy).
    /// </summary>
    Task<OcrResult> ExtractTextAsync(Stream pdfContent);
}

/// <summary>
/// Result of a text-extraction attempt.
/// </summary>
/// <param name="Text">The extracted (possibly empty) text.</param>
/// <param name="LooksLikeScannedImage">
/// True when extraction produced little/no text — a hint to the caller (or a composite provider)
/// that this content is likely a scanned image with no embedded text layer, and that an OCR
/// fallback provider should be tried instead of trusting this near-empty result.
/// </param>
public record OcrResult(string Text, bool LooksLikeScannedImage);
